/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedMedicationsRouteImport } from './routes/_authenticated/medications'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPrescriptionsRouteImport } from './routes/_authenticated/prescriptions'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'
import { Route as AuthenticatedHealthCategoryRouteImport } from './routes/_authenticated/health.$category'
import { Route as AuthenticatedHealthCategoryIndexRouteImport } from './routes/_authenticated/health.$category.index'
import { Route as AuthenticatedHealthCategoryModeRouteImport } from './routes/_authenticated/health.$category.$mode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMedicationsRoute =
  AuthenticatedMedicationsRouteImport.update({
    id: '/medications',
    path: '/medications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrescriptionsRoute =
  AuthenticatedPrescriptionsRouteImport.update({
    id: '/prescriptions',
    path: '/prescriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHealthCategoryRoute =
  AuthenticatedHealthCategoryRouteImport.update({
    id: '/health/$category',
    path: '/health/$category',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHealthCategoryIndexRoute =
  AuthenticatedHealthCategoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHealthCategoryRoute,
  } as any)
const AuthenticatedHealthCategoryModeRoute =
  AuthenticatedHealthCategoryModeRouteImport.update({
    id: '/$mode',
    path: '/$mode',
    getParentRoute: () => AuthenticatedHealthCategoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AuthenticatedAccountRoute
  '/home': typeof AuthenticatedHomeRoute
  '/medications': typeof AuthenticatedMedicationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/prescriptions': typeof AuthenticatedPrescriptionsRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/health/$category': typeof AuthenticatedHealthCategoryRouteWithChildren
  '/health/$category/$mode': typeof AuthenticatedHealthCategoryModeRoute
  '/health/$category/': typeof AuthenticatedHealthCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AuthenticatedAccountRoute
  '/home': typeof AuthenticatedHomeRoute
  '/medications': typeof AuthenticatedMedicationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/prescriptions': typeof AuthenticatedPrescriptionsRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/health/$category/$mode': typeof AuthenticatedHealthCategoryModeRoute
  '/health/$category': typeof AuthenticatedHealthCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/medications': typeof AuthenticatedMedicationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/prescriptions': typeof AuthenticatedPrescriptionsRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/health/$category': typeof AuthenticatedHealthCategoryRouteWithChildren
  '/_authenticated/health/$category/$mode': typeof AuthenticatedHealthCategoryModeRoute
  '/_authenticated/health/$category/': typeof AuthenticatedHealthCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/home'
    | '/medications'
    | '/onboarding'
    | '/prescriptions'
    | '/api/chat'
    | '/chat/$threadId'
    | '/health/$category'
    | '/health/$category/$mode'
    | '/health/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/home'
    | '/medications'
    | '/onboarding'
    | '/prescriptions'
    | '/api/chat'
    | '/chat/$threadId'
    | '/health/$category/$mode'
    | '/health/$category'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/account'
    | '/_authenticated/home'
    | '/_authenticated/medications'
    | '/_authenticated/onboarding'
    | '/_authenticated/prescriptions'
    | '/api/chat'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/health/$category'
    | '/_authenticated/health/$category/$mode'
    | '/_authenticated/health/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medications': {
      id: '/_authenticated/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof AuthenticatedMedicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prescriptions': {
      id: '/_authenticated/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof AuthenticatedPrescriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health/$category': {
      id: '/_authenticated/health/$category'
      path: '/health/$category'
      fullPath: '/health/$category'
      preLoaderRoute: typeof AuthenticatedHealthCategoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health/$category/': {
      id: '/_authenticated/health/$category/'
      path: '/'
      fullPath: '/health/$category/'
      preLoaderRoute: typeof AuthenticatedHealthCategoryIndexRouteImport
      parentRoute: typeof AuthenticatedHealthCategoryRoute
    }
    '/_authenticated/health/$category/$mode': {
      id: '/_authenticated/health/$category/$mode'
      path: '/$mode'
      fullPath: '/health/$category/$mode'
      preLoaderRoute: typeof AuthenticatedHealthCategoryModeRouteImport
      parentRoute: typeof AuthenticatedHealthCategoryRoute
    }
  }
}

interface AuthenticatedHealthCategoryRouteChildren {
  AuthenticatedHealthCategoryModeRoute: typeof AuthenticatedHealthCategoryModeRoute
  AuthenticatedHealthCategoryIndexRoute: typeof AuthenticatedHealthCategoryIndexRoute
}

const AuthenticatedHealthCategoryRouteChildren: AuthenticatedHealthCategoryRouteChildren =
  {
    AuthenticatedHealthCategoryModeRoute: AuthenticatedHealthCategoryModeRoute,
    AuthenticatedHealthCategoryIndexRoute:
      AuthenticatedHealthCategoryIndexRoute,
  }

const AuthenticatedHealthCategoryRouteWithChildren =
  AuthenticatedHealthCategoryRoute._addFileChildren(
    AuthenticatedHealthCategoryRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMedicationsRoute: typeof AuthenticatedMedicationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPrescriptionsRoute: typeof AuthenticatedPrescriptionsRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedHealthCategoryRoute: typeof AuthenticatedHealthCategoryRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMedicationsRoute: AuthenticatedMedicationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPrescriptionsRoute: AuthenticatedPrescriptionsRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedHealthCategoryRoute:
    AuthenticatedHealthCategoryRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
